resources:
  - name: repo_node
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration
      path: manishas-jfrog/example-mono-repo    # replace with your repository name
      branches:
        include: master
      files:
        include: ^node-image\/.+

pipelines:
  - name: pipeline_build_node_image
    steps:
      - name: run_java_build
        type: Bash
        configuration:
          affinityGroup: dockerGroup
          inputResources:
            - name: repo_node
        execution:
          onExecute:
            - echo "I am running the Node build pipeline"
            - cat $res_repo_node_resourcePath/node-image/readme-node.md
