resources:
  - name: repo_java_image
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration
      path: manishas-jfrog/example-multiple-pipeline-config-files    # replace with your repository name
      branches:
        include: master
      files:
        include: ^java-image\/.+

pipelines:
  - name: pipeline_build_java_image
    steps:
      - name: run_java_build
        type: Bash
        configuration:
          affinityGroup: dockerGroup
          inputResources:
            - name: repo_java_image
        execution:
          onExecute:
            - echo "I am running the Java build pipeline"
            - cat $res_repo_java_image_resourcePath/readme-java.md
